package org.benjob.smartmailbox.model;
// Generated Dec 29, 2015 10:41:30 PM by Hibernate Tools 4.3.1.Final

/**
 * Mailbox generated by hbm2java
 */
public class Mailbox implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    
    private long id;
    private Address Address;
    private Integer Number;
    private Person Owner;
    private String InternetAddress;

    public Mailbox() {
    }

    public Mailbox(Address Address, Integer Number, Person Owner, String InternetAddress) {
        this.Address = Address;
        this.Number = Number;
        this.Owner = Owner;
        this.InternetAddress = InternetAddress;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Address getAddress() {
        return this.Address;
    }

    public void setAddress(Address Address) {
        this.Address = Address;
    }

    public Integer getNumber() {
        return this.Number;
    }

    public void setNumber(Integer Number) {
        this.Number = Number;
    }

    public Person getOwner() {
        return this.Owner;
    }

    public void setOwner(Person Owner) {
        this.Owner = Owner;
    }

    public String getInternetAddress() {
        return this.InternetAddress;
    }

    public void setInternetAddress(String InternetAddress) {
        this.InternetAddress = InternetAddress;
    }

}
