package org.benjob.smartmailbox.model;
// Generated Dec 29, 2015 10:31:07 PM by Hibernate Tools 4.3.1.Final

/**
 * Parcel generated by hbm2java
 */
public class Parcel implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    
    private long id;
    private Person Recipient;

    public Parcel() {
    }

    public Parcel(Person Recipient) {
        this.Recipient = Recipient;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Person getRecipient() {
        return this.Recipient;
    }

    public void setRecipient(Person Recipient) {
        this.Recipient = Recipient;
    }

}
