package org.benjob.smartmailbox.model;
// Generated Dec 22, 2015 12:11:09 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * PersonAddresses generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class PersonAddresses implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    
    private long id;
    private Person Person;
    private Address Address;
    private boolean isOwner;
    private Date StartDate;
    private Date EndDate;

    public PersonAddresses() {
    }

    public PersonAddresses(Person Person, Address Address, boolean isOwner, Date StartDate, Date EndDate) {
        this.Person = Person;
        this.Address = Address;
        this.isOwner = isOwner;
        this.StartDate = StartDate;
        this.EndDate = EndDate;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Person getPerson() {
        return this.Person;
    }

    public void setPerson(Person Person) {
        this.Person = Person;
    }

    public Address getAddress() {
        return this.Address;
    }

    public void setAddress(Address Address) {
        this.Address = Address;
    }

    public boolean isIsOwner() {
        return this.isOwner;
    }

    public void setIsOwner(boolean isOwner) {
        this.isOwner = isOwner;
    }

    public Date getStartDate() {
        return this.StartDate;
    }

    public void setStartDate(Date StartDate) {
        this.StartDate = StartDate;
    }

    public Date getEndDate() {
        return this.EndDate;
    }

    public void setEndDate(Date EndDate) {
        this.EndDate = EndDate;
    }

}
