package org.benjob.smartmailbox.model;
// Generated Dec 22, 2015 12:11:09 PM by Hibernate Tools 4.3.1.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Person generated by hbm2java
 */
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Person implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    
    private long id;
    private String FirstName;
    private String MiddleName;
    private String LastName;
    private String PhoneNumber;
    private String Key;

    public Person() {
    }

    public Person(String FirstName, String MiddleName, String LastName, String PhoneNumber, String Key) {
        this.FirstName = FirstName;
        this.MiddleName = MiddleName;
        this.LastName = LastName;
        this.PhoneNumber = PhoneNumber;
        this.Key = Key;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getFirstName() {
        return this.FirstName;
    }

    public void setFirstName(String FirstName) {
        this.FirstName = FirstName;
    }

    public String getMiddleName() {
        return this.MiddleName;
    }

    public void setMiddleName(String MiddleName) {
        this.MiddleName = MiddleName;
    }

    public String getLastName() {
        return this.LastName;
    }

    public void setLastName(String LastName) {
        this.LastName = LastName;
    }

    public String getPhoneNumber() {
        return this.PhoneNumber;
    }

    public void setPhoneNumber(String PhoneNumber) {
        this.PhoneNumber = PhoneNumber;
    }

    public String getKey() {
        return this.Key;
    }

    public void setKey(String Key) {
        this.Key = Key;
    }

}
