package org.benjob.smartmailbox.model;
// Generated Dec 29, 2015 10:31:07 PM by Hibernate Tools 4.3.1.Final

/**
 * PostOffice generated by hbm2java
 */
public class PostOffice implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    
    private long id;
    private String Street;
    private String City;
    private String State;
    private String Country;
    private Integer ZipCode;

    public PostOffice() {
    }

    public PostOffice(String Street, String City, String State, String Country, Integer ZipCode) {
        this.Street = Street;
        this.City = City;
        this.State = State;
        this.Country = Country;
        this.ZipCode = ZipCode;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getStreet() {
        return this.Street;
    }

    public void setStreet(String Street) {
        this.Street = Street;
    }

    public String getCity() {
        return this.City;
    }

    public void setCity(String City) {
        this.City = City;
    }

    public String getState() {
        return this.State;
    }

    public void setState(String State) {
        this.State = State;
    }

    public String getCountry() {
        return this.Country;
    }

    public void setCountry(String Country) {
        this.Country = Country;
    }

    public Integer getZipCode() {
        return this.ZipCode;
    }

    public void setZipCode(Integer ZipCode) {
        this.ZipCode = ZipCode;
    }

}
